### ISSUE TITLE
[Feature Request]: Nerf Ocean Creepers

### ISSUE THREAD

**Issue by StellaBiscuit** [Toadstool-Studios/Creeper-Overhaul#76]
### Is your feature request related to a problem?

I found Ocean Creepers to be pretty cheap as you really have no time to react when on a boat and your health just drains in mere seconds

### Solution(s)

Nerf Ocean Creepers damage, short and simple

### Describe alternatives you've considered

Make them more visible as they blend really well with other fish which is cheap and causes unfair death in early game

### Mod Version

2.0.9

### Mod Loader Version

1.19.2 - 0.14.21

### Mod Loader

Fabric

**Comment by Flyvee** [comment]
I would like to add that with ocean creepers right now, wearing full iron, it can still kill you in 3 hits in 2 seconds. You can't outswim them and on boat you barely go faster than them. And lastly a Lot of them spawn in the warm ocean biome all the time. So possible nerfs is either less damage or pure poison damage so it leaves you on 1 heart or make them slower so that they are more like moving landmines, or make their spawning rarer or only at night.

**Comment by kiwiandoesthings** [comment]
This is definitely something that needs to happen.
